name: Git Diff

on:
  pull_request:
    types: [labeled]


jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.git-diff.outputs.DIFF_FILES }}
      count: ${{ steps.git-diff.outputs.DIFF_COUNT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: LuisLiraC/git-diff@feat/action-file
        id: git-diff
        with:
          patterns: '*.toml,*.rs'

      - name: Get the output time
        run: |
          echo "Files ${{ steps.git-diff.outputs.DIFF_FILES }}"
          echo "Count ${{ steps.git-diff.outputs.DIFF_COUNT }}"

  lint:
    runs-on: ubuntu-latest
    needs: [get-diff]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linter
        run: |
          echo "Linting the following files:"
          echo "${{ needs.get-diff.outputs.files }}"
          echo "Total files: ${{ needs.get-diff.outputs.count }}"
