name: Git Diff

on:
  pull_request:
    types: [labeled]


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: LuisLiraC/hello-world-action@main
        id: git-diff
        with:
          patterns: '*.toml,*.rs'

      - name: Get the output time
        run: |
          echo "Files ${{ steps.git-diff.outputs.DIFF_FILES }}"
          echo "Count ${{ steps.git-diff.outputs.DIFF_COUNT }}"
