on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y libssl1.1 ca-certificates
      - name: Hello world action step
        uses: ./
        id: git-diif
